alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias upd='sudo pacman -Sy'
alias ins='sudo pacman -S'
alias cl='clear'
alias remove='sudo pacman -R'
alias py='python3'
alias upg='sudo pacman -Syu'
alias runserver='./manage.py runserver'
alias runserver80='./manage.py runserver 0.0.0.0:8000'
alias jn='jupyter notebook'
alias ydl='youtube-dl --extract-audio --audio-format mp3'
#alias vim='vim -n'
alias migrate='./manage.py migrate'
alias startapp='./manage.py startapp'
alias makemigrations='./manage.py makemigrations'
alias wifi='sudo systemctl restart network-manager.service'
alias createsu='./manage.py createsuperuser'
alias shell='./manage.py shell'
alias fm='dde-file-manager'
alias pixel='./Android/Sdk/emulator/emulator @Pixel_API_Q'
alias nexus='./Android/Sdk/emulator/emulator @nexus'
#alias reshap = 'mount -o remount,size='
alias inotify='sudo sysctl fs.inotify.max_user_watches=999999999'
alias gp='git push origin master'
alias ga='git add .'
alias gc='git commit -m '
alias gs='git status'
alias gpl='git pull'
alias mm='makemigrations'
alias awesome='cd ~/.config/awesome/'
alias gdiff='git diff'
alias sbash='source ~/.bashrc'
alias pacrm='sudo rm /var/lib/pacman/db.lck'
alias chzsh='chsh -s /bin/zsh'
alias chbash='chsh -s /bin/bash'
alias ydl='youtube-dl --extract-audio --audio-format mp3'
#find . -name '*.pyc' | xargs -n 1 git rm --cached
alias log="git log --shortstat --author 'Umesh Chaudhary' --since '10am'"
alias brightness="xrandr --output HDMI1 --brightness"
alias tuch="xinput map-to-output 11 HDMI1"
alias extend="xrandr --output HDMI1 --same-as eDP1"
alias ayulogic_up='nmcli con up 535dc113-f29a-4d7d-b632-6c7bbe8d873d ayulogic'
alias ayulogic_down='nmcli con down 535dc113-f29a-4d7d-b632-6c7bbe8d873d ayulogic'
alias newwifi='nmcli con up 776e26d4-fb72-4e5a-bd0d-0ea5608d434f'
alias volup='pactl -- set-sink-volume 0 +10%'
alias voldown='pactl -- set-sink-volume 0 -10%'
alias tmuxn="tmux new -s"
alias a="tmux attach -t"
alias attach="tmux attach -t"
alias killtmux="pkill -f tmux"
alias weather="curl wttr.in"
alias bxt_staging='ssh -v -i ~/Fetchly/pems/Fetchly-Sci.pem ec2-user@ec2-34-222-81-24.us-west-2.compute.amazonaws.com'
alias bxt_prod='ssh -v -i ~/Fetchly/pems/Fetchly-Sci.pem ec2-user@ec2-34-209-232-207.us-west-2.compute.amazonaws.com'
alias vim='nvim'
alias n='nvim'
alias vide='neovide'
alias drops="cd ~/workspace/fetch.ly/drops-dashboard"
alias drops-fe="cd ~/workspace/fetch.ly/drops-dashboard/frontend"
alias drops-be="cd ~/workspace/fetch.ly/drops-dashboard/backend"
alias edit_nvim="cd ~/.config/nvim && nvim ."
alias edit_alias="nvim ~/.bash_aliases"
alias edit_zsh="nvim ~/.zshrc"
alias edit_drops="cd ~/workspace/fetch.ly/drops-dashboard && tmuxn drops"
alias edit_api_campus="cd ~/workspace/fetch.ly/api.campuslegends.com && nvim ."
alias edit_campus="cd ~/workspace/fetch.ly/campus-legends-react-app && nvim ."
alias dbuild="COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build"
alias dup="docker-compose up"
alias gty="git commit --date='1 day ago' -m 'Your commit message'"
